### ISSUE TITLE
Error ModuleNotFoundError: No module named 'librtlsdr'

### ISSUE THREAD

**Issue by Klammraute** [nootedandrooted/rtl-sdr-close-call-monitor#1]
Hi, the logging script shows me taht no librtlsdr is installed, but i am pretty shure it is.

sudo python3 csv_logging.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/rtlsdr/__init__.py", line 23, in <module>
    try:                from  librtlsdr import librtlsdr
ModuleNotFoundError: No module named 'librtlsdr'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rx/rtl-sdr-close-call-monitor/csv_logging.py", line 4, in <module>
    from rtlsdr import RtlSdr
  File "/usr/local/lib/python3.10/dist-packages/rtlsdr/__init__.py", line 24, in <module>
    except ImportError: from .librtlsdr import librtlsdr
  File "/usr/local/lib/python3.10/dist-packages/rtlsdr/librtlsdr.py", line 41, in <module>
    librtlsdr = load_librtlsdr()
  File "/usr/local/lib/python3.10/dist-packages/rtlsdr/librtlsdr.py", line 25, in load_librtlsdr
    driver_files += [find_library('rtlsdr'), find_library('librtlsdr')]
  File "/usr/lib/python3.10/ctypes/util.py", line 341, in find_library
    _get_soname(_findLib_gcc(name)) or _get_soname(_findLib_ld(name))
  File "/usr/lib/python3.10/ctypes/util.py", line 147, in _findLib_gcc
    if not _is_elf(file):
  File "/usr/lib/python3.10/ctypes/util.py", line 99, in _is_elf
    with open(filename, 'br') as thefile:
FileNotFoundError: [Errno 2] No such file or directory: b'liblibrtlsdr.a'
root@rx:/home/rx/rtl-sdr-close-call-monitor#

**Comment by nootedandrooted** [comment]
Hi, try running it without sudo (root privileges). I tried to run it with the sudo command and I got the same error. Works just fine without it. Hope this helps!

**Comment by Klammraute** [comment]
the error persists, even without sudo rights.

**Comment by Klammraute** [comment]
which system/OS do you using and which version of Python3?

**Comment by Klammraute** [comment]
found a solution: dont run it with sudo/root privileges

**Comment by nootedandrooted** [comment]
Yeah I think I told you the solution four days ago. Also this has nothing to do with the actual script.

**Comment by Klammraute** [comment]
thank you, randhelm zutzelbauch! :)
